### ISSUE TITLE
Unable to deal with non-UTF-8 filenames

### ISSUE THREAD

**Issue by mgiuca** [fusepy/fusepy#2]
Fusepy was recently modified to treat all filenames and metadata as Unicode strings instead of byte strings. This works when filenames are UTF-8, but breaks when filenames or other metadata contain byte sequences that are not valid UTF-8 characters.

As I originally reported [here](http://code.google.com/p/fusepy/issues/detail?id=32#c5), user code should be written to deal with bytes, not the other way around. On POSIX operating systems, file paths are NOT specified as being UTF-8 or any specific Unicode encoding. The only correct way to deal with filenames on Unix is to treat them as byte strings. Most software I've seen treats them as UTF-8, but at the file system level, they are binary strings and any FUSE implementation would be broken if it didn't support non-UTF-8 filenames.

In other words, I need to be able to cd to a FUSE-mounted file system, open Python 3, and type this:

```
>>> import os
>>> open(b'd\xe9j\xe0_vu.txt', 'w').close()
>>> os.listdir(b'.')
[b'd\xe9j\xe0_vu.txt']
```

In most shells, if you `ls` this file, it will display as `d?j?_vu.txt`. But it is a perfectly valid Latin-1-encoded filename. If fusepy encoded the filename as a Unicode string before sending it to the user code, it would either throw an exception in this case, or corrupt the filename.

The current version of fusepy (the GitHub version) breaks this assumption. Commit 2590f48 adds an 'encoding' argument to the FUSE constructor, and then decodes all the bytes values to strs with this encoding before giving them to the user-supplied operations, and encodes all strs supplied by user code before giving them back to the operating system. Unfortunately, it isn't a correct solution to simply say "pick an encoding before you start". File systems must be able to support different files with different encodings on their names.

If you run memory.py and then perform my above example, you get this:

```
Traceback (most recent call last):
  File "fuse.py", line 402, in _wrapper
    return func(*args, **kwargs) or 0
  File "fuse.py", line 410, in getattr
    return self.fgetattr(path, buf, None)
  File "fuse.py", line 640, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 2: invalid continuation byte
```

Alternatively, create the `b'd\xe9j\xe0_vu.txt'` file somewhere on a normal drive, and then run the loopback.py example on the directory containing that file. Attempting to 'ls' the directory results in this exception:

```
Traceback (most recent call last):
  File "fuse.py", line 402, in _wrapper
    return func(*args, **kwargs) or 0
  File "fuse.py", line 586, in readdir
    if filler(buf, name.encode(self.encoding), st, offset) != 0:
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce9' in position 1: surrogates not allowed
```

First things first: I have created a relatively incomplete test script which is in my [tests](https://github.com/mgiuca/fusepy/tree/tests) branch. It tests mounting the memory filesystem and creating a binary filename, and this test currently fails in both Python 2 and 3. (Note that this test passes in Python 2 on the latest Google Code version of fusepy, SVN r65.)

I have also prepared a branch which fixes this issue in the ideal way for me: [bytes](https://github.com/mgiuca/fusepy/tree/bytes). This branch removes all of the encode/decode calls and the encoding parameter to the FUSE constructor. All Operation methods accept and return plain bytes objects. This is ideally the way it should work. I have made sure this works on Python 2.7 and 3.2 (with 2to3). Note that I have updated the memory, loopback and context examples, but not the sftp example, as I was unable to test it.

However, it may be too drastic to accept this change: for one thing, it breaks on Python 2.5 and earlier, because it introduces b'' notation. (This is necessary to properly run on Python 3.) For another thing, it may break existing users who have adopted the Unicode strings in the current version.

I have thought a bit about another less drastic solution: work the way that Python 3's [os.listdir](http://docs.python.org/dev/library/os.html#os.listdir) works. The Python docs [explain a bit about how this works here](http://docs.python.org/dev/library/os.html#file-names-command-line-arguments-and-environment-variables). Basically, byte strings are converted into unicode strings, but if any bytes are invalid in that encoding, they are replaced with U+DCxx where xx is the byte value. This is a bit hacky, but it allows the user to deal with Unicode strings, and then roundtrip properly back into bytes objects. Fusepy could employ the same technique on Python 3 when sending and receiving strings from the user's Operations methods. It is easy to implement: just call encode and decode with errors='surrogateescape'.

However, this only works in Python 3. In Python 2, you should absolutely not be encoding filenames and metadata as Unicode strings, because the Python 2 str type allows you to represent binary data but treat it as text.

If you go with this approach, I would also like the option of using bytes in my own code. Perhaps if I call the FUSE constructor with encoding=None, it will deal with bytes objects, and if I specify an encoding, it will use surrogateescape?

I'm happy to help work on the solution to this problem. I recognise that my branch is not a final solution, but the start of a discussion (which is why I haven't made a pull request). But I think it is necessary to resolve this issue in one way or another, because the current behaviour makes it impossible to implement a robust filesystem, and that is unacceptable to me.

**Comment by dsoprea** [comment]
So.. After three-years, have we fixed the Unicode support in any regard?

**Comment by eestrada** [comment]
@dsoprea Looking at the current codebase, it is still very Unicode-centric and does not use anything to mitigate potential issues (such as using `surrogateesacpe`).

Probably the fastest/simplest way to address this is to use `surrogateesacpe`. That way, current users expecting Unicode will still get Unicode, but it shouldn't break horrendously when encountering filenames that have encodings that the default decoder can't handle.

**Comment by eestrada** [comment]
@dsoprea Perhaps you are right. @s-m-e was pushing me to do more drastic changes and I was digging in my heels a bit for fear of breaking backwards compatibility. Hearing you (someone with [a relatively popular `fusepy` dependent project](https://github.com/dsoprea/GDriveFS)) push for a fix that potentially breaks backwards compatibility makes me reconsider my initial stance.

This project got caught in the early Python 3 zeitgeist of Unicoding everything, regardless of whether it actually made sense for the given use case or not. I did the same thing with a lot of my projects around the same time too.

![Hyperbole and a half: Unicode all the Things](https://memegenerator.net/img/instances/250x250/11335129/unicode-all-the-things.jpg)

I would like to fix it "the proper way," as you put it. Just to be sure we are on the same page, here is my vision of fixing this properly: I think @mgiuca was 100% correct. Since `fusepy` is POSIX system boundary code, then forcing Unicode conversions pretty much anywhere in `fusepy` is broken behavior. I would instead just use raw `bytes` for everything. 99.999% of the time the filepaths can be totally opaque and the code doesn't need to care at all what is actually inside the bytes objects. The only time anyone should care what is inside `bytes` objects is when working with paths, but even that isn't very hard since the `os.path` module in Python 3 supports both `bytes` as well as (Unicode) `str` objects. If it is just clearly understood that everything returns `bytes` all the time, then callers of the library can simply convert to Unicode if/when they need it. `fusepy` should avoid making any decisions about encoding/Unicode until the last possible moment by leaving it up to the user/caller.

Is that what you meant by fixing it properly, @dsoprea, or are you intending something else? I want to make sure we are on the same page.

Since I am moving the project to Semantic Versioning, I think such a change would be considered a major version change, since I would guess that it breaks backward compatibility. @dsoprea How would you deal with the breaking change in your project? Would you just lock off on a previous version of `fusepy` until you could make sure your project worked with the updated `fusepy` version?

Sidenote: @mgiuca has the beginnings of a [testsuite for `fusepy`](https://github.com/mgiuca/fusepy/blob/tests/test.py) that we can use to exercise the code and make sure that we don't cause regressions moving forward.

**Comment by dsoprea** [comment]
Yep. That's what I had in mind, though you might, by default, marshal the outputs back to strings unless the user has provided configuration that indicates it's okay to return bytes. Kind-of like __future__ for _fusepy_. Then, when do actually do a release to the next major version, flip the default to returning bytes. Major versions in SemVer are allowed to be backwards-incompatible anyway (as you said). Just put a loud warning in the documentation that brings this to peoples' attention ahead of time. It's going to still hurt people that have a > or >= for their _pip_ requirement, but we've done our best to mitigate it and we all know how often Google and other large brands indiscrimantly break projects with backwards-incompatible changes. It's unfortunate, but you just have to be wise with how and when you do it.

My second suggestion (or, arguably, the alternative to the above) is that you might maintain two separate branches for six months or a year in order to show grace to the legacy integrations while providing people the newer implementation to develop/verify against. I'd put the new sexiness on the master branch and legacy on a branch. Most of your risk is going to be package use, not from people cloning the project. Then, since you're developing on two different branches, you can also maintain two different version series (2.x and 3.x, legacy and new) and push off both branches. If consumers can't deal with the overhead of reintegrating against the mainline packages, they can just be careful to stay on the legacy series.

Make sure you get Terence's to transfer his PyPI project, by the way.

I think those unit-tests should be our first, highest priority. What we've been talking about is probably the riskiest activity that you're going to have to deal with on this project and there's already enough potential for user disruption without introducing bugs through a lack of even minimal unit-test coverage. You can make them minimal, but they can also emphasis type-checking of inputs (make sure they're strings) and outputs (make sure strings are being returned, at least until the next step when you change how the outputs are handled) since we know this is going to be potentially problematic.

No strategy is going to be perfect. Just focus on things that will both minimize risk and maximize your ability to find and squash bugs when they happen.

**Comment by eestrada** [comment]
@dsoprea I like your approach: have a switch to get proper behavior now, then change the default behavior at the next major release. If someone still needs the previous "unicode-y" behavior, they can explicitly flip the switch back again. It leaves a immediate upgrade path for people who want the bytes behavior now, and a good "downgrade" path for those who wan the Unicode behavior moving forward.

I agree that we need to testing in place first. It can be a very basic framework, but enough that we can add new test cases as needed would be enough to get us started.

**Comment by paulo-raca** [comment]
My 2 cents: Filenames are not binary blobs.

In the old days, my windows partition had filenames encoded in iso8859-1, and it was really frustrating when filenames showed up with a bunch of � in the middle of it. Later on I learned that I could add `iocharset=iso8859-1` to the mount options and my filenames were nice again.

Apparently this is no longer necessary to set the iocharset manually on a FAT partition, but this ilustrates that filenames are text, and the kernel will even perform charset encoding/decoding.

That said, if you really want to work with raw bytes, why not?

I suggest we update `FUSE` and `FUSELL` with 2 new methods, `encode` and `decode`, which will be no-ops if encoding is set to None.

If that works for you, I can write a PR

**Comment by terencehonles** [comment]
@paulo-raca I agree, I believe we should try to encourage encoding the filenames, but if someone wants to deal with binary because they know best or they need to perform their own decoding based on path or some other fallback encoding scheme they should be able to do so.
